#straps_msgs

# Constants of keypoint indices and names.

uint8 NOSE = 0
uint8 LEFT_EYE = 1
uint8 RIGHT_EYE = 2
uint8 LEFT_EAR = 3
uint8 RIGHT_EAR = 4
uint8 LEFT_SHOULDER = 5
uint8 RIGHT_SHOULDER = 6
uint8 LEFT_ELBOW = 7
uint8 RIGHT_ELBOW = 8
uint8 LEFT_WRIST = 9
uint8 RIGHT_WRIST = 10
uint8 LEFT_HIP = 11
uint8 RIGHT_HIP = 12
uint8 LEFT_KNEE = 13
uint8 RIGHT_KNEE = 14
uint8 LEFT_ANKLE = 15
uint8 RIGHT_ANKLE = 16

# string[] KEYPOINT_NAMES = [ "nose", "left_eye", "right_eye", "left_ear", "right_ear", "left_shoulder", "right_shoulder", "left_elbow", "right_elbow", "left_wrist", "right_wrist", "left_hip", "right_hip", "left_knee", "right_knee", "left_ankle", "right_ankle" ]


